name: depoly app django
on:
   push:
     branches: [ main ]
jobs:
  build-and-test:
     runs-on: ubuntu-latest

     steps:
      - name: chekout repostory
        uses: actions/checkout@v4

      - name: test code python
        uses: actions/setup-python@v4  
        with:
          python-version: '3.13.1'

      - name: install flake8 and test
        run: |
         pip install flake8  
         flake8 . || true

      - name: se connecter a docker hub
        uses: docker/login-action@v2   
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build image docker
        run: |
          docker build -t  ${{ secrets.DOCKER_IMAGE_NAME }} .

      - name:  afficher image
        run: docker images

      - name: scan avec trivy
        uses: aquasecurity/trivy-action@master
        with: 
         image-ref: ${{ secrets.DOCKER_IMAGE_NAME }}
         severity: LOW,MEDIUM,CRITICAL
         scanners: vuln
         ignore-unfixed: true

      - name: Monitor Snyk project
        uses: snyk/actions/setup@master
        continue-on-error: true
        env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
         command: monitor 
         args: --all-projects

      - name: Test Snyk vulnerabilities
        uses: snyk/actions/setup@master
        env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
         command: test 
         args: --all-projects
        continue-on-error: true 

      - name: tag and pousser image dans docker hub 
        run: |
         docker tag ${{ secrets.DOCKER_IMAGE_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
         docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest

         